name: Deploy to Railway

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh

      - name: Configure Railway Project Token
        run: |
          mkdir -p ~/.railway
          echo "${{ secrets.RAILWAY_PROJECT_TOKEN }}" > ~/.railway/token

      - name: Deploy to Railway
        run: |
          railway up --detach --service nest-api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_TOKEN }}
          RAILWAY_PROJECT_TOKEN: ${{ secrets.RAILWAY_PROJECT_TOKEN }}